Homework 1
sieday/cs464-homework pull request #1
Opened 2023-10-04 23:49 UTC by sieday

This includes both the answers to the selector game and my palindrome checker.

I am not confident with the Airbnb style guide or my bootstrap classes - would love any feedback around those that y'all have.

2023-10-05 21:11 UTC, dvan2 requested changes
Hey Sieday.  I've reviewed the code changes and I just mainly saw some unnecessary code that could be removed and just a naming convention that needs to be changed.

2023-10-05 21:11 UTC, dvan2 commented on hw1/02-palindrome.js
> +function palindrome_check(user_input) {
I believe it is recommended to use pascal case when naming functions and variable instances.  `palindomeCheck` instead of `palindrome_check`.

Airbnb link: https://github.com/airbnb/javascript#naming-conventions

2023-10-05 21:11 UTC, dvan2 commented on hw1/02-palindrome.js
> +  } else if (user_input === '') {
For this base cases since you already have a return statement, I believe we can remove the `else` statements because it will never execute since the function will return before the else statement.
```
if(userInput < 0) {
  return inputErr();
}
if(userInput === '') {
  return inputErr();
}
```
I think this is just a little easier to read and removes any unnecessary code.  You could even combine those two statements with `||` since they will do the same thing if true.

2023-10-05 21:11 UTC, dvan2 commented on hw1/02-palindrome.js
> +  console.log('False');
I think we can remove `console.log` statements because it is unnecessary code.

2023-10-05 21:11 UTC, dvan2 commented on hw1/02-palindrome.js
> +  return false;
I'm not sure if this function should really return a boolean value.  From the looks of it the function call doesn't really catch the value either.  This function always returns false no matter what so maybe we just change it to `return` instead.

2023-10-06 02:41 UTC, deanajackson commented on hw1/02-palindrome.js
> +  } else if (user_input === '') {
I think this may be part of the style guide too if I'm interpreting correctly. See 16.3 to verify

2023-10-06 03:05 UTC, deanajackson requested changes
Hey Sienna,

Nice work here! Great job sticking to the style guide witht the quotes and code blocks.
I like how you used const in favor of let (and var, of course) where it made sense. It was also good how you caught multiple "bad" user input cases. Also your use of helper functions is a great example. David did that too and I think my code could have benefited from multiple functions. 
Great that you dove into some styling. I have a lot to learn about Bootstrap still so I don't feel confident giving feedback there. I found myself wanting to add a css file the whole time. haha
I ran the wave extentsion and it threw one error regarding the form labels. We talked about it today in class as a good refresher. Easy to miss since the logic of the Palidrome detectr was top of mind.

2023-10-06 03:05 UTC, deanajackson commented on hw1/02-palindrome.js
> +    return input_err();
When you backspace all entered values, it throws the negative number error unnecessarily. I think it is interpreting null as < 0?

2023-10-06 03:05 UTC, deanajackson commented on hw1/02-palindrome.js
> +  return;
I remeber in Karla's classes it was pounded into our heads to always return *something*. I don't see this discussed explicitly in the style guide but also every single instance of "return" in the style guide returns something. Might be something to consider as a best practice.

2023-10-06 03:05 UTC, deanajackson commented on hw1/02-palindrome.js
> +  return palindrome_check(user_input);
Here I wonder if it is necessary to put the function call in a return statement, rather than just calling the function?

2023-10-06 03:05 UTC, deanajackson commented on hw1/02-palindrome.js
> +function handleInput() {
New and funky one for all of us **Funtions 7.1** in the style guide:  Use named function expressions instead of function declarations

2023-10-06 03:05 UTC, deanajackson commented on hw1/02-palindrome.html
>            <label>Enter a positive number:</label>
Form labeling issues that cause error in Wave extension

2023-10-06 18:39 UTC, sieday commented on hw1/02-palindrome.js
> +    return input_err();
Good catch, thanks for noticing this. I switched it over to just remove the error for an empty value, I assumed empty text would be an error case, but I guess an empty box is a palindrome. Nothing backwards is still nothing.

2023-10-06 19:00 UTC, merged